### ISSUE TITLE
FamilySearchPlaceState docs are invalid

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-php#41]
See http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Extensions.FamilySearch.Rs.Client.FamilySearchPlaceState.html

**Comment by justincy** [comment]
That might be due to outdated docs

**Comment by justincy** [comment]
@jimmyz How do you update the docs?

**Comment by jimmyz** [comment]
The docs are generated via [ApiGen](http://www.apigen.org).

I used a modified version of the [ThemeBootstrap](https://github.com/ApiGen/ThemeBootstrap) project in order to get the search drop-down and a few other things to be wide enough for the long namespacing of the gedcomx-php classes. I'll push the changes to a forked version of the theme.

The command to generate it with the custom theme is found here:
https://gist.github.com/jimmyz/f1a6cf18dc114850a881

**Comment by jimmyz** [comment]
Okay, here's my fork of the ThemeBootstrap project:
https://github.com/jimmyz/ThemeBootstrap

**Comment by jimmyz** [comment]
I ran the process to generate a new version of the docs, which is now deployed, but generating the doc gave the following Parse error:

Parse error: Class Gedcomx\Extensions\FamilySearch\Rs\Client\FamilySearchPlaceState was redeclared (previously declared in file /workspace/sdks/php/gedcomx-php/src/Extensions/FamilySearch/FamilySearchPlaceState.php).

This could be the reason for the inaccurate docs. Perhaps the FamilySearchPlaceState is found in multiple files.
